# Generated by Django 4.2.7 on 2023-11-03 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_equipment', models.CharField(max_length=16, verbose_name='тип оборудования')),
                ('mask_equipment', models.CharField(max_length=80, verbose_name='маска серийного номера')),
            ],
            options={
                'verbose_name_plural': 'Тип оборудования',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=16, verbose_name='код оборудования')),
                ('serial_number', models.CharField(max_length=10, verbose_name='серийный номер')),
                ('text', models.CharField(max_length=512, verbose_name='примечание')),
                ('fk_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='equipment.equipmenttype')),
            ],
            options={
                'verbose_name_plural': 'Оборудование',
            },
        ),
    ]
