# Generated by Django 4.2.7 on 2023-11-03 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='serial_number',
            field=models.CharField(max_length=10, unique=True, verbose_name='серийный номер'),
        ),
    ]
