# Generated by Django 4.2.7 on 2023-11-04 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_alter_equipment_serial_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='grade',
        ),
    ]
